version: '3.7'

services:
  backend:
    container_name: myapp_backend
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=3000
    volumes:
      - ./:/app/project
    working_dir: /app/project
    ports:
      - "3000:3000"
    links:
      - mysqldb
    depends_on:
      - mysqldb
  mysqldb:
    container_name: myapp_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'mySqlAdm'
      MYSQL_DATABASE: 'myWallet'
      MYSQL_PASSWORD: 'mySqlAdm'