version: '3.7'

services:
  backend:
    container_name: myapp_backend
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=3000
    volumes:
      - ./src:/var/www/app-patrimonio/src
    working_dir: /var/www/app-patrimonio
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: myapp_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'mySqlAdm'
      MYSQL_DATABASE: 'myWallet'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'mySqlAdm'
    volumes:
    - myapp_mysql_data:/var/lib/mysql

volumes:
  myapp_mysql_data: